packages:
  - 11ty/**
  - slidev/**

catalogs:
  11ty:
    "@11ty/eleventy": 3.1.2
    budoux: 0.7.0
    markdown-it: 14.1.0
    markdown-it-footnote: 4.0.0
  slidev:
    "@slidev/cli": 52.11.1
    "@slidev/theme-default": 0.25.0
    vue: 3.5.26
  root:
    gh-pages: 6.3.0

catalogMode: strict